### ISSUE TITLE
Log-in

### ISSUE THREAD

**Issue by stevenkyritsis** [Creatige/Creatige-App#4]

**Comment by Elmojica** [comment]
Backend

- [x] Connect APIs to the app
- [x] Have a user class in the database
- [x] Create a user in the database
- [x] Verify user from list of users in the back4app database
          *(Log in and authenticate a user by username and password)
- [x] Create a parse class 
- [x] User is persisted on the app
- [x] Define Data models(like they do in the schema) for the user data 
- [x] Set main activity to be log in activity

**Comment by pedropachecog** [comment]
Frontend:

- [x] Create screen
- [x] Implement navigation to Register 
- [x] Implement navigation to main Activity on successful login
