### ISSUE TITLE
Create 1

### ISSUE THREAD

**Issue by stevenkyritsis** [Creatige/Creatige-App#6]

**Comment by pedropachecog** [comment]
Frontend

- [x] Make activity that will hold the bottom navigation menu and all the other screens besides Login and Register
- [x] Make fragment for Create
- [x] Implement navigation to other activities
- [x] Create fragment for text to image

**Comment by Elmojica** [comment]
Backend

- [x] possibly parse the data to be able to make the API call from stablehorde 
- [x] get back the data returned from stablehorde to allow it to be displayed
- [x] submit prompt and generated image to user posts table
