### ISSUE TITLE
Detail

### ISSUE THREAD

**Issue by pedropachecog** [Creatige/Creatige-App#7]
- [x] Build activity
- [x] Build comments RecyclerView
- [x] Build comments submit box
- [x] Load image and details into activity
- [x] Load comments into activity
- [x] Add commenting functionality

**Comment by Elmojica** [comment]
- [x] Get image from the post table 
- [x] get user 
- [x] time of creation


Stretch

- [x] Get comments from the Post Table 
- [x] Be able to write a comment on a post and save the comment to the database
