### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by Elmojica** [Creatige/Creatige-App#9]

**Comment by pedropachecog** [comment]
- [x] Create activity
- [x] Navigate to other screens
- [x] Create RecyclerView for image generations
- [x] Load data
- [x] Load image generations

**Comment by Elmojica** [comment]
- [x] get user profile picture
- [x] get username
- [x] get number of user creations
- [x] get user creations (list of all images)
           *ensure that there is a table or array holding the data necessary to access all of the creations that the user has made


stretch

- [ ] be able to store multiple images in a singular post?
